FROM postgres:15-alpine

# Copiar script de inicialización
COPY init_read_db.sql /docker-entrypoint-initdb.d/init_read_db.sql

# Asegurar que el script tenga permisos de ejecución
RUN chmod 755 /docker-entrypoint-initdb.d/init_read_db.sql

# Exponer puerto
EXPOSE 5432
